apiVersion: apps/v1
kind: Deployment
metadata:
  name:  flask-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: lucys99/flask-backend:1.0.10
        ports:
        - containerPort: 5001
        lifecycle:
          preStop:
            ## TODO: implement this so that backend.py handles SIGTERM and logs a message
            exec:
              command: ["/bin/sh", "-c", "echo 'SIGTERM received, shutting down gracefully...'"]

        volumeMounts:
        - name: model-volume
          mountPath: /shared-volume
          readOnly: true  # Backend only needs read access
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  flask-backend-service # TODO: Specify a unique service name if deploying multiple services
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
    - port: 5001
      targetPort: 5001
